services:
  - type: web
    name: bux-taxes-web
    runtime: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URI
        fromDatabase:
          name: bux-taxes-db
          property: connectionString
      - key: PAYLOAD_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_URL
        fromContext: instanceUrl

databases:
  - name: bux-taxes-db
    databaseName: bux_taxes
    user: postgres
    plan: free
